cycler==0.11.0
fpdf==1.7.2
kiwisolver==1.3.1
matplotlib==3.3.4
numpy==1.19.5
pandas==1.1.5
Pillow==8.4.0
pkg_resources==0.0.0
progress==1.6
pyparsing==3.0.7
python-dateutil==2.8.2
pytz==2021.3
scipy==1.5.4
six==1.16.0
